### ISSUE TITLE
Project Summary Changing Milestone to affected Milestone

### ISSUE THREAD

**Issue by gilmaxter** [dubeaud/bugnet#100]
ON the project Summary  I can see the milestone section, and i am wondering how hard it would be to change it to show information based on affected milestone. Is something like that possible  and what should i do to accomplish it.

**Comment by dubeaud** [comment]
You could change this stored procedure to affected milestone https://github.com/dubeaud/bugnet/blob/master/src/BugNET.Database/Stored%20Procedures/BugNet_Issue_GetIssueMilestoneCountByProject.sql

**Comment by gilmaxter** [comment]
Just doing that would be enough to switch it to use afflicted Milestone to show up on project summary ?

**Comment by gilmaxter** [comment]
And if this is correct what file or files need to be moved over to the live server ? is it just the BugNet.Database.dll or is it more or something else ?

**Comment by dubeaud** [comment]
Looks ok,  you need to change CREATE to ALTER and run it on your database server.

**Comment by gilmaxter** [comment]
Alrighty thank you very much i can see it working, though now when i click on the link it is still going by the milestone ID and not the Affected milestone ID on Issue List what needs to change on this?
