### ISSUE TITLE
not able to add members to project while edit project

### ISSUE THREAD

**Issue by pankajgarg29** [dubeaud/bugnet#102]
Hi,

I have recently added bugnet on windows azure and created a new project. When i created the project i added only one member to it. Now i am trying to add more users (4 users) to it but there is no save button on members page. Even i move the users from left to right, it moves them but as i refresh the page, added user gone away.

Please help me on this.

Thanks & Regards
Pankaj

**Comment by dubeaud** [comment]
Check the page for JavaScript errors. There may be a script that is not loading or executing properly.

**Comment by dubeaud** [comment]
any luck?

**Comment by pankajgarg29** [comment]
I am not able to add members from edit project section. But I got it from
user edit section, from there I can add user to the project.

Thanks
Pankaj

On Wednesday, March 25, 2015, Davin Dubeau <notifications@github.com> wrote:
> any luck?
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci5.googleusercontent.com/proxy/IUPLRgGhSWsiogOtUETD3AaAjodwrZm5P_OQuu0t_t78R3zPVWE8D_LpAKh3mtH7qDzJEww7G-I32bnnZZ12__EKJD0PerNijrC5CIHRsd-RnLcvGrtxP1MjNvNiT5Qge886fre6ue86utfUXzJUC5o3q9aelA=s0-d-e1-ft#https://github.com/notifications/beacon/AIIPHw_-SgEeZXKBAqezU5_oKsv2C3veks5n4fHagaJpZM4Dy443.gif
>
