### ISSUE TITLE
I want to change the  application's language,but I don't know how to set it,could you help me? Thanks!

### ISSUE THREAD

**Issue by dannyxj** [dubeaud/bugnet#105]

**Comment by dannyxj** [comment]
I have read the documents about translation,but I don't understand your mean, could you tell each procedure to change the language(ex. chinese)? Thank you very much for your help, have a nice day!!

**Comment by Novadys-IT** [comment]
You have to make a copy of each file <filename>.resx to <filename>.xx-XX.resx where "xx-XX" means your 2-letters country code. For example if you are planning to translate to chinese, file "Default.aspx.resx" have to be copied to "Default.aspx.cn-CN.resx" and so on.

Then you have to edit each resx file and replace english text into your language translation. There are some free tools over the web that make this process easier. Personally I use Zeta resource Editor (http://www.zeta-resource-editor.com/index.html).

When finished (it's a long way to go...) don't forget to set new language from Administration->Configuration->Languages menu.

**Comment by ionutasandului** [comment]
Hi. I have the Romanian translation installed, and is set in Administration->Configuration->Languages menu. however, the only page translated is the default page. Everything else is still in english, including e-mail notifications. i did someting wrong? i need to setup someting else ?

**Comment by Novadys-IT** [comment]
Sorry for late answer. Email notifications make use of template files, you have to translate them in romanian separately.
