### ISSUE TITLE
server error "Invalid BugNet_P114_CFV object name"

### ISSUE THREAD

**Issue by g689087** [dubeaud/bugnet#107]
Hi,
from today i receive this error.
So i have created this table with 2 fields (IssueId, ProjectId) and now error don't raise.
But in list bugs i don't see any items/records (that they exists).
Which is the error? What is "BugNet_P114_CFV" table? I don't see it in any upgrade script...
Many thanks

**Comment by dubeaud** [comment]
Log in as administrator and browse to /Administration/Projects/ProjectList.aspx and then click  regenerate custom field views.

**Comment by g689087** [comment]
It doesn't function, error continue.
I have exexute this script and now it functions.

CREATE VIEW [dbo].[BugNet_P114_CFV]
 AS 
 SELECT i.ProjectId, i.IssueId, i.[IsClosed], i.[Disabled]
FROM
 BugNet_IssuesView i
 WHERE i.ProjectId = 114

Many thanks
