### ISSUE TITLE
Issue Id

### ISSUE THREAD

**Issue by lolaparra** [dubeaud/bugnet#109]
Hello:

It is possible have different Id issue? For example, I have some different projects and I would like that the issue Id starts at each project with 1. At least for new projects I would like to change this, but I don't know if it is easy or not.
Thank you.

**Comment by dubeaud** [comment]
The issue id is an incrementing number across all projects and can't be changed. This is a common design in most issue trackers.

**Comment by lolaparra** [comment]
Ok, thank you.
