### ISSUE TITLE
Procedure or function 'BugNet_Project_CreateNewProject' expects parameter '@AttachmentStorageType', which was not supplied.

### ISSUE THREAD

**Issue by ccs-sgriffin** [dubeaud/bugnet#110]
Hi,

When I try to create a new project or update a current project, I m getting errors relating to the AttachmentStorageType please see below 

Procedure or function 'BugNet_Project_CreateNewProject' expects parameter '@AttachmentStorageType', which was not supplied.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Data.SqlClient.SqlException: Procedure or function 'BugNet_Project_CreateNewProject' expects parameter '@AttachmentStorageType', which was not supplied.
Source Error: 
Line 160:                                      };
Line 161:
Line 162:                if (BLL.ProjectManager.SaveOrUpdate(project))
Line 163:                {
Line 164:                    ProjectId = project.Id;

qlException (0x80131904): Procedure or function 'BugNet_Project_CreateNewProject' expects parameter '@AttachmentStorageType', which was not supplied.]
   System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) +1754082
   System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) +5295874
   System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) +242
   System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) +1682
   System.Data.SqlClient.SqlDataReader.TryConsumeMetaData() +59
   System.Data.SqlClient.SqlDataReader.get_MetaData() +90
   System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString) +365
   System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite) +1325
   System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite) +175
   System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method) +53
   System.Data.SqlClient.SqlCommand.ExecuteScalar() +149
   BugNET.Providers.DataProviders.SqlDataProvider.ExecuteScalarCmd(SqlCommand sqlCmd) +247
   BugNET.Providers.DataProviders.SqlDataProvider.CreateNewProject(Project newProject) +2065
   BugNET.BLL.ProjectManager.SaveOrUpdate(Project entity) +395
   BugNET.Administration.Projects.UserControls.ProjectDescription.Update() in d:\bugnet-473d5407aa53 - Updating\src\BugNET_WAP\Administration\Projects\UserControls\ProjectDescription.ascx.cs:162
   BugNET.Administration.Projects.AddProject.btnNext_Click(Object sender, EventArgs e) in d:\bugnet-473d5407aa53 - Updating\src\BugNET_WAP\Administration\Projects\AddProject.aspx.cs:119
   System.Web.UI.WebControls.Button.OnClick(EventArgs e) +9633962
   System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument) +103
   System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument) +10
   System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument) +13
   System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData) +35
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +1724

While the field has been moved to Host settings, the stored procedures to create and update a project  require this.

Has anyone any idea what may be happening  when i try to create or update a project? 

Thanks
 Seamus

**Comment by dubeaud** [comment]
What version are you running?

**Comment by hoffmannlin** [comment]
hello,

i just use branch-master

i got same error when i just install and create first project


and i didn't saw  @AttachmentStorageType at  src\Library\Providers\DataProviders\SqlDataProvider\SqlDataProvider.cs

but pocedure have this parameter

**Comment by ccs-sgriffin** [comment]
Davin 

I m updating our current build of bugnet and the last SQL in the sqldataprovider folder was  1.5.258.0.SqlDataProvider. I took down your latest build and built this locally with a local copy of our database  and encountered the problem when testing this

**Comment by ccs-sgriffin** [comment]
Any update as to when this bug will be fixed?

**Comment by uspenskiyan** [comment]
Hello.
Have the same error on 1.6.327 version from source code. I'm looking at source only one day, but, as I see, You changed src/BugNET.Database/Stored Procedures/BugNet_Project_CreateNewProject.sql, and install run src/BugNET_WAP/Providers/DataProviders/SqlDataProvider scripts, where the last change of SP was in 1.5.258.0. and there's no your changes. Is it right?
