### ISSUE TITLE
Hidden default fields still showing on created ticket - demo

### ISSUE THREAD

**Issue by kdubato** [dubeaud/bugnet#111]
I don't know if this has to do with the demo, but I have turned off a few fields within the Project Admin settings > Defaults.  They do not appear when I create a new ticket, but they show up when I view the ticket.   Is this supposed to happen?

Here is a screenshot that shows what I am talking about

![image](https://cloud.githubusercontent.com/assets/987601/7144910/46185d4a-e2ae-11e4-9b5a-6cb4f4896308.png)

**Comment by dubeaud** [comment]
The demo is at an older version.  In the latest version 1.6.339 or BN Pro 1.5.105 there are two columns; one that controls the visibility on the new issue screen and the other on the edit issues screen.

**Comment by kdubato** [comment]
Wow, thanks for the quick follow up.  I wasn't sure if I should actually create a ticket, but thanks again.

**Comment by dubeaud** [comment]
No problem :)
