### ISSUE TITLE
Very hard to see required flags on Custom Fields

### ISSUE THREAD

**Issue by efficiondave** [dubeaud/bugnet#113]
When you hit save on an issue and a required field isn't filled out selected, it's very hard to see the Required notifier. It's just black normal size/weight text that appears by the field. There should be some kind of larger alert that not all required fields were filled out and the required flag should be red and bold.

**Comment by dubeaud** [comment]
What version of the app and particular page are you referring to because fields are highlighted using the bootstrap required field styles typically.

**Comment by efficiondave** [comment]
Version: 1.6.339.0
It only seems to be a problem with Custom Fields... The title field lights up nicely. But for the Custom Fields, none of the required classes (has_error, text-danger validation-error) are rendered.

**Comment by efficiondave** [comment]
And it's occurring on the IssueDetail page

**Comment by efficiondave** [comment]
I was able to fix this by updating DisplayCustomFields.ascx.cs line 297 with:

                    var valReq = new RequiredFieldValidator
                    {
                        ControlToValidate = FIELD_VALUE_NAME,
                        Text = string.Format(" ({0})", GetGlobalResourceObject("SharedResources", "Required")).ToLower(),
                        Display = ValidatorDisplay.Dynamic,
                        CssClass = "text-danger validation-error",
                        SetFocusOnError = true
                    };

**Comment by dubeaud** [comment]
Thanks, I will update the code with this.

**Comment by elbaloo** [comment]
@dubeaud, seems like @efficiondave's code is already [in](https://github.com/dubeaud/bugnet/blob/master/src/BugNET_WAP/UserControls/DisplayCustomFields.ascx.cs#L297).
