### ISSUE TITLE
Custom Field - Select Box Multiple

### ISSUE THREAD

**Issue by kdubato** [dubeaud/bugnet#114]
I was wondering if it's possible to create a custom field or a modify a pre-built field so that users can select multiple objects.

For example, I would like to create a field called System.  It is possible that one bug can affect more than one system, so I would like our users to be able to select multiple systems instead of just one from a  dropdown.  Possible?

Thanks.

**Comment by dubeaud** [comment]
Unfortunately, right now that isn't possible. All fields are single selection.
