### ISSUE TITLE
Application Configuration Default Url

### ISSUE THREAD

**Issue by spoiledtechie** [dubeaud/bugnet#115]
I host the BugNet project on one server, but it supports many different projects and websites.  So I might have one of my websites with one project on their, but then another one of my websites with a project on there.

Allowing users to add new issues to each of these projects starts to get complicated due to each different project.  Right now, I have it using 5 different websites.  http://support.www.com, then http://support.www2.com etc with the same installation.

The problem lies with the default url, that when its used through out the site, I can only use one url in that field, rather than the current 5 sites that I have.  So my suggestion is to add a default url per project OR (which makes more sense), if I leave that text box blank, that it just pulls the url currently being used by the user who modifies issues, adds issues etc.

So when I modify an issue at http://support.www2.com, I would like to make sure the domain is used when it sends a notification etc...

Thanks!

**Comment by dubeaud** [comment]
Haven't really considered this scenario before. I guess the idea was that you host multiple projects under one domain / host header.

**Comment by spoiledtechie** [comment]
I understand.  Thanks!
