### ISSUE TITLE
Can't Upload Attachments on V 1.6.339.0

### ISSUE THREAD

**Issue by spoiledtechie** [dubeaud/bugnet#121]
I am unable to upload attachments to specific issues.  It keeps saying there is an issue, but when I check logs, I see nothing.  I have given the uploads directory and App_Data directory full permissions for the NETWORK SERVICE user and still can't upload attachments.  Help?

**Comment by dubeaud** [comment]
Check the account that your app pool is running under.  That is the account that should have read / write permissions on the upload folders. Or you could switch to database storage of attachments.

**Comment by lolaparra** [comment]
Hello:
I have a similar problem, when I try to attach an image an error is launched, 
Application Error - /bugnet/Issues/IssueDetail.aspx
An error has occured in processing your request.

In the Attachment configuration I have the next parameters:
![image](https://cloud.githubusercontent.com/assets/11923522/8425992/19afc49c-1f0c-11e5-8409-a48434f73252.png)
