### ISSUE TITLE
Unregistered Users

### ISSUE THREAD

**Issue by NeilN1** [dubeaud/bugnet#126]
Setting this up on an internal intranet.  As far as I can see, there's no way for an employee to create an issue without logging in.  Is this correct?  All we want is a quick way for staff to open issues, entering their email address as a contact point, without having access to the issues list or anything else.

**Comment by PeterDefendo** [comment]
Using windows domain authentication might work for you? https://bugnet.codeplex.com/wikipage?title=Configure%20Active%20Directory%20/%20Windows%20Authentication

**Comment by dubeaud** [comment]
There is also the ability to submit issues by email but yes you do require a login to submit issues.  

You could also create a generic account to enter issues and give everyone the password but you lose a but of traceability that way.
