### ISSUE TITLE
StatusEditVisibility after a successful upgrade -

### ISSUE THREAD

**Issue by inkumc** [dubeaud/bugnet#131]
Please any clue to why I'm unable to view or create new issues after the upgrade?

Thanks,

BugNET 

Upgrading BugNET
Upgrade Status Report
Current Assembly Version: 1.6.339.0
Current Database Version: 1.5.265.0
00:00:00 - Upgrading To Version: 1.6.339.0
00:00:00.0312010 -    Executing Script: 1.6.307.0.SqlDataProvider.sql Success
00:00:00.4992160 -    Executing Script: 1.6.327.0.SqlDataProvider.sql Success
Upgrade Complete
Click Here To Access Your BugNET Installation

Server Error in '/' Application.

StatusEditVisibility

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.IndexOutOfRangeException: StatusEditVisibility

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[IndexOutOfRangeException: StatusEditVisibility]
   System.Data.SqlClient.SqlDataReader.GetOrdinal(String name) +318
   System.Data.SqlClient.SqlDataReader.get_Item(String name) +25
   BugNET.Providers.DataProviders.SqlDataProvider.TGenerateDefaultValueListFromReader(SqlDataReader returnData, List`1& defaultList) +2441
   BugNET.Providers.DataProviders.SqlDataProvider.ExecuteReaderCmd(SqlCommand sqlCmd, GenerateListFromReader`1 gcfr, List`1& list) +179
   BugNET.Providers.DataProviders.SqlDataProvider.GetDefaultIssueTypeByProjectId(Int32 projectId) +297
   BugNET.Administration.Projects.UserControls.ProjectDefaultValues.ReadDefaultValuesForProject() +73
   BugNET.Administration.Projects.UserControls.ProjectDefaultValues.Initialize() +131
   BugNET.Administration.Projects.EditProject.LoadTab(Int32 selectedTab) +1129
   BugNET.Administration.Projects.EditProject.AdminMenu_ItemCommand(Object sender, RepeaterCommandEventArgs e) +141
   System.Web.UI.WebControls.Repeater.OnBubbleEvent(Object sender, EventArgs e) +55
   System.Web.UI.WebControls.RepeaterItem.OnBubbleEvent(Object source, EventArgs e) +164
   System.Web.UI.Control.RaiseBubbleEvent(Object source, EventArgs args) +84
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +3804

**Comment by dubeaud** [comment]
Try going into the administration section and under the default values click save.  Was this project a cloned project?

**Comment by inkumc** [comment]
I reinstalled and error went away.  Thanks Davin
