### ISSUE TITLE
Error when attachment

### ISSUE THREAD

**Issue by lolaparra** [dubeaud/bugnet#133]
Hello:
I have a similar problem, when I try to attach an image an error is launched, 
Application Error - /bugnet/Issues/IssueDetail.aspx
An error has occured in processing your request.

In the Attachment configuration I have the next parameters:
![image](https://cloud.githubusercontent.com/assets/11923522/8426024/683a0d7a-1f0c-11e5-8e43-8f02459da126.png)

**Comment by dubeaud** [comment]
How big is the file?  You may have to increase the max size allows in the web.config. look for the httpruntine element.

**Comment by lolaparra** [comment]
My file (jpg) is only 50KB if I change the file size limit to 100000 bytes it would be work, but not, still appear the same error.

**Comment by dubeaud** [comment]
Set custom errors off in the web.config and try again. The root error should be shown.
```xml
<customErrors mode="Off" />
```

**Comment by lolaparra** [comment]
After change the <customErrors mode ="Off"/> and try to attach the image another different error is launched.
![error_bugnet1](https://cloud.githubusercontent.com/assets/11923522/8521154/6aebfb30-23e1-11e5-80a1-82d24c13e804.png)

**Comment by dubeaud** [comment]
Try putting you file extensions in as 
```
.jpg;.png;.docx
```

**Comment by lolaparra** [comment]
I have changed the extensions to .jpg;.png;.docx and now when I try to attach don't show the last error window but still appear the message in the attachment section:
There was an error saving the attachment datetime.jpg.

**Comment by dubeaud** [comment]
Check the log viewer to see if anything was reported in there.

**Comment by lolaparra** [comment]
There is no anything for today, the last entry was in 4/10/2015

**Comment by dubeaud** [comment]
What version are you using and what attachment storage type?

**Comment by lolaparra** [comment]
The BugNET 1.6.339.0 version and I am trying to attach a jpg file or png.

**Comment by dubeaud** [comment]
By default, attachments are stored in the database , or the file system. You can set this in the project settings.  File system requires you have the IIS app pool account have write permissions on the Uploads directory but usually you would get an error if this isn't so.  

I am not sure what the problem is at the moment. Can you try a different file name just incase.

**Comment by lolaparra** [comment]
Thank you for your recommendations. I didn't know that I have to allow the attachments, so I was looking the properties of the project and finally I have found the check box to allow the attachments to the project. 
I'm sorry for the inconvenience. Thank you for being patient with me.

**Comment by dubeaud** [comment]
The attachments tab shouldn't have shown for projects in which it is disabled though.

**Comment by lolaparra** [comment]
This is another different issue I suppose. Finally I have could attach the jpg file. Thank you again.
