### ISSUE TITLE
Gravatar should use SSL

### ISSUE THREAD

**Issue by dylanvdmerwe** [dubeaud/bugnet#135]
I am getting security warnings when using Bugnet over https. This frightened me at first until I looked at the network requests. Basically gravatars are being pulled over http instead of https. 

Gravatar requests should go over https when hosted in https environment. 

![capture](https://cloud.githubusercontent.com/assets/2852839/8571232/bcd5fed2-2585-11e5-89bc-827e5050a183.PNG)

**Comment by dubeaud** [comment]
I agree.

**Comment by dubeaud** [comment]
This has already been checked in
