### ISSUE TITLE
Script to export/import everything about project

### ISSUE THREAD

**Issue by erict-powersoft** [dubeaud/bugnet#136]
I need to transfer 3 projects to a new server that is also running bugnet.  Is there a script to help me perform this task?  Thanks!

**Comment by dubeaud** [comment]
I don't have one but I am not sure if anyone else has made one before.

**Comment by erict-powersoft** [comment]
OK, I'll probably make one after the summer holidays.  Where I should I 
post it for others?
Eric

**Comment by dubeaud** [comment]
You can create a new enhancement issue and attach the script there.
