### ISSUE TITLE
admin account doesn't have administrator rights. Need help

### ISSUE THREAD

**Issue by aznarepse** [dubeaud/bugnet#137]
Just installed bugnet in a IIS 8 and the install went without errors but when I login with admin/password, I cannot see the administrator menus and when I try to create a new project, I get the access denied page.
I have had a look into the db and the admin user is in the BugNet_UserRoles tables as 1 (super user).
The version of BugNet is 1.6.339.0.

Cannot do anything... :( Any idea or direction where to look at?

**Comment by aznarepse** [comment]
Got it! Sorry if I wasted someone's time... I had been all day trying to make it work.
The problem was:
In the ISS, the authorization mode was to anonymous disable, Forms enabled and Windows enabled... they weren't working together. The settings are now: anonymous enabled and forms enabled only. It works this way.
Thank you

**Comment by dubeaud** [comment]
No problem. Glad you got it working.
