### ISSUE TITLE
Delete custom fields

### ISSUE THREAD

**Issue by dubeaud** [dubeaud/bugnet#14]
**This issue was imported from [CodePlex](http://bugnet.codeplex.com/workitem/166)**

**[dylanvdmerwe](http://www.codeplex.com/site/users/view/dylanvdmerwe)** wrote 2014-02-12 at 07:05
In Project Administration I have a DropDownList custom field. There are many items in this list. The custom field on my system shows me a list of all clients that I can assign an issue to.

When I press and confirm the deletion of an item in the drop down list nothing happens.

I am assuming that these items are already allocated somewhere else, but in this case the user should be prompted to reassign all items to another item in the list, or on deletion items are reassigned to the first item in the list (if available).

**Comment by kalkie** [comment]
Hi David,

I will also try to solve this one if you agree.

**Comment by kalkie** [comment]
I did some investigation and the issue only occurs if the field value is actually used in an issue. The delete action results into a call to the storedproc BugNet_ProjectCustomFieldSelection_DeleteCustomFieldSelection which does the following:

```
DECLARE
	@CustomFieldId INT

SET @CustomFieldId = (SELECT TOP 1 CustomFieldId 
						FROM BugNet_ProjectCustomFieldSelections 
						WHERE CustomFieldSelectionId = @CustomFieldSelectionIdToDelete)

BEGIN TRAN
	UPDATE BugNet_ProjectCustomFieldValues
	SET CustomFieldValue = NULL
	WHERE CustomFieldId = @CustomFieldId
							
	DELETE 
	FROM BugNet_ProjectCustomFieldSelections 
	WHERE CustomFieldSelectionId = @CustomFieldSelectionIdToDelete
COMMIT TRAN
```

The first part of setting the CustomFieldValue to NULL fails as the column cannot have a null value. 

@dubeaud Do you know what the intended behavior is of this stored proc?

**Comment by dubeaud** [comment]
The idea was to set all values to null for that custom field then delete it. The custom field value field should allow nulls and looks to be a bug.
