### ISSUE TITLE
New issue creation exception

### ISSUE THREAD

**Issue by sgualmo** [dubeaud/bugnet#142]
i already installed and configured BUGNET but when i go to place a new issue, regardless of the user logged in , it is detected the exception attached
![errorbugnet](https://cloud.githubusercontent.com/assets/13979563/9491036/63b18aaa-4bec-11e5-8de4-c320aec60d88.png)

What's the problem? 
It's urgent, Thanks a lot. Ciao.
Stefano

**Comment by larshg** [comment]
You might find a clue what to do here: http://stackoverflow.com/questions/26189699/asp-net-mvc4-configuration-error-after-installing-mysql-connector-net

If I can recognize the error correctly.
