### ISSUE TITLE
Ability to move ticket from one project to another

### ISSUE THREAD

**Issue by philwig** [dubeaud/bugnet#143]
We're always creating tickets in the "wrong project" by mistake. The fix we have is to delete the issue and then manually create it again in the "right project", once you spot the error.

Is there an easier way we are missing?

If not, can someone maybe suggest some SQL which would do the job - running a script would be easier than the above. I dare say I can work this out, but some reassurance that it's sensible would be nice.

Actually:
  UPDATE [BugNet].[dbo].[BugNet_Issues]
  SET ProjectId = 2
  WHERE IssueID = 4546

Would presumably do it, assuming I know the ProjectId and IssueID (sic). Anyone know if that will break anything?

**Comment by philwig** [comment]
That seems to work perfectly.

**Comment by dubeaud** [comment]
It may break things as each project has its own id values for status , component etc values.

**Comment by philwig** [comment]
Noted. As it happens we use the same values for all projects. Plus usually someone just puts one in the wrong project (with defaults in those types of field) and then as soon as someone looks at it (before they add content) they realize it's in the wrong place.

So long as it's not going to corrupt the DB (it seems ok), then I guess it's my risk. So far it seems fine.
