### ISSUE TITLE
How to make a backup of the database

### ISSUE THREAD

**Issue by topcatarg** [dubeaud/bugnet#147]
Hello. We are trying to set up a nice daily backup of our database. is there a standard procedure to do that?
We try opening the db inside SSMS but is exclusive taken by bugnet. Is that correct?

**Comment by dubeaud** [comment]
You may be running it in user instance mode, if you attach the database you can then backup via ssms.

**Comment by topcatarg** [comment]
You say SSMS? we have to open it using the same user that bugnet is using? we are opening SSMS using the sa user. is not that the correct one?

**Comment by dubeaud** [comment]
Using SA is perfectly fine.  Just recycle IIS or shut it off to unlock the database then attach it in SMSS.

**Comment by topcatarg** [comment]
ok, will try that tomorrow.. Will that afect bugnet operation? Or I have to deatach after the backup. I would like to make a daily backup, auto.
