### ISSUE TITLE
404 on Content/css

### ISSUE THREAD

**Issue by fgbk** [dubeaud/bugnet#149]
Hi, i have upgrade from 1.1 to 1.6 and i am having errors with styling and login. It says "Failed to load resource: the server responded with a status of 404 (Not Found)" for the following Login.aspx:9 GET http://localhost/BugNET/Content/css?v=ZnrNzV03UMExjPzuyRXyIYj9yXT5HG_Hpa_t5cs5yzA1

**Comment by dubeaud** [comment]
This is a duplicate of https://github.com/dubeaud/bugnet/issues/31

**Comment by fgbk** [comment]
I added the fixed from #31 and that fixed the bundles issue but i still have an issues with content/css
