### ISSUE TITLE
Problem with rewrite

### ISSUE THREAD

**Issue by kaadner** [dubeaud/bugnet#151]
I've installed BugNet on a server (manual install) and the site is running. But the layout is not as expected (see attached image), and some of the links return 404. I suspect that URL rewrite is not working, and that might be why the layout is wrong too.

I've checked that the site is running .Net 4.5 and we have other .Net sites on the server, that use rewrite without any problems.

Any suggestions to what I need to check?

![bugnet](https://cloud.githubusercontent.com/assets/14974309/10275952/035f8e34-6b4c-11e5-98a2-6d46a643aae4.jpg)

**Comment by dubeaud** [comment]
It is probably this issue https://github.com/dubeaud/bugnet/issues/31

**Comment by kaadner** [comment]
That works! Thank you.
