### ISSUE TITLE
How to add file attachment 

### ISSUE THREAD

**Issue by rushdan** [dubeaud/bugnet#157]
Hello Support,

I would like to attach image when create a new Issue but I won't . How to do that ?
![how to add attachment](https://cloud.githubusercontent.com/assets/6026860/10630904/e5f8a592-780c-11e5-8d5e-4f643428f607.png)

Thanks

**Comment by dubeaud** [comment]
I believe you can just drag and drop an image to the editor and it will
embed the image as base64.

**Comment by rushdan** [comment]
Thanks for reply.

I have see the button Choose File to upload . I have upload attachment and save. But when I see the issue in details, the image cannot view.

![button attachment](https://cloud.githubusercontent.com/assets/6026860/10655493/c7dd7218-78a7-11e5-891a-5b2a79095c98.png)

In configuration, I have set the format image can be upload. But still not display the image

![attachment settings](https://cloud.githubusercontent.com/assets/6026860/10655496/cd751776-78a7-11e5-95a5-84c74460f52e.png)

Thanks.

From
Rushdan

**Comment by dubeaud** [comment]
If you uploading an image that way it will show under the attachments tab
on an issue.  The alternative is to drag and drop it to the  issue
description editor to add it inline with your text.

**Comment by rushdan** [comment]
I see the attachment tab.

Then, I upload the image and press Add Attachment button.
The error come out 

![error when add attachment](https://cloud.githubusercontent.com/assets/6026860/10664110/1fce2fb2-78f3-11e5-8761-cc3d9e6dfffc.png)


 There was an error saving the attachment listing complete status only.png.

I dont know what does it error mean ?

Could you tell me about this ?

Thanks

**Comment by rushdan** [comment]
Hello support,

I testing again. I create the issue to myself. Add the attachment then save. No attachment view in attachment tab. 

Please help how to solve this.

Thanks

**Comment by dubeaud** [comment]
You can possible get more details from the error log in BugNET found in the
administration panel. If the image is larger than 2mb increase the size
validation in the settings. If it is larger than 4mb you have to change the
http max request length in the web.config.

**Comment by rushdan** [comment]
>> You can possible get more details from the error log in BugNET found in the
administration panel. 

I log-in as administrator. No error found in the administration panel but error still occur.

![log viewer](https://cloud.githubusercontent.com/assets/6026860/10664907/c19477a6-78f9-11e5-94ed-8a0ea478ec71.png)

>>  If the image is larger than 2mb increase the size validation in the settings.

My image file size just 7KB but it still fired the error even the attachment setting has set limit for 2MB only

![attachment size limit](https://cloud.githubusercontent.com/assets/6026860/10664931/e6133ae0-78f9-11e5-98ce-31ef111b3ec1.png)
 
Hope this help to solve this issue.

Thanks

**Comment by energywave** [comment]
I had problem with attachments too and now I'm using them correctly so maybe I can be of help.
Please note that extensions are case sensitive (PLEASE FIX THAT!!!) so I repeat every extension in lowercase and uppercase.
Having said that the only format in wich I managed to use the attachment is by specifiying allowed extensions using this format (copy - paste from my list):
*.jpg;*.JPG;*.png;*.PNG;*.txt;*.TXT;*.sql;*.SQL;*.log;*.LOG;*.ini;*.INI;*.bmp;*.BMP;*.doc;*.DOC;*.docx;*.DOCX;*.pdf;*.PDF;*.xls;*.XML;*.zip;*.ZIP;*.7z;*.7Z;*.xlsx;*.XLSX;*.XLS
Hope this can help.

**Comment by rushdan** [comment]
Thanks for your help.

Having said that the only format in wich I managed to use the attachment is by specifiying allowed extensions using this format (copy - paste from my list):
.jpg;.JPG;.png;.PNG;.txt;.TXT;.sql;.SQL;.log;.LOG;.ini;.INI;.bmp;.BMP;.doc;.DOC;.docx;.DOCX;.pdf;.PDF;.xls;.XML;.zip;.ZIP;.7z;.7Z;.xlsx;.XLSX;*.XLS

I follow your way but still has an error.

**Comment by energywave** [comment]
Sorry, having pasted my extensions list asterisk characters was removed from the string.
I'll attach a screenshot of the field so that you can understand how I inserted the string. Let's try this.

![estensioni](https://cloud.githubusercontent.com/assets/2051567/10671177/817920c8-78e9-11e5-83a4-d86cc13e103c.PNG)

**Comment by rushdan** [comment]
> I'll attach a screenshot of the field so that you can understand how I inserted the string. Let's try this.

I have try example as yours but still get the error. I cant upload the attachment. And the file size is below 50K

![addsterisk](https://cloud.githubusercontent.com/assets/6026860/10673216/2c03d5a0-7927-11e5-9128-71d02d95cff5.png)

**Comment by rushdan** [comment]
sorry, this issue is still open. I can't solve it.

**Comment by dubeaud** [comment]
Are you using file system or database attachments?

What is the error in the error log?
