### ISSUE TITLE
How to filter specific issue in Issue Summary ?

### ISSUE THREAD

**Issue by rushdan** [dubeaud/bugnet#159]
In Issue summary, how to listing only specific status ? For example I want it listing issue which is not solve yet .

![listing complete status only](https://cloud.githubusercontent.com/assets/6026860/10657304/d09cebe0-78bb-11e5-8953-34acd9e137cc.png)

Thanks

**Comment by larshg** [comment]
When you set up the various status's you need to tick the "Is closed state" - then all those that are "complete" shouldn't be visible.

**Comment by rushdan** [comment]
Thanks , it works

**Comment by rushdan** [comment]
I

**Comment by rushdan** [comment]
Sometime , I need to reopen the issue again for some purpose. How to do that ?

Thanks

**Comment by dubeaud** [comment]
Visit the issue then set the status to any value that isn't marked as "Is Closed" status.
