### ISSUE TITLE
How to delete the issue in Issue Summary

### ISSUE THREAD

**Issue by rushdan** [dubeaud/bugnet#160]
Hello team support,

How to delete the issue ?

![delete the issue or ticket](https://cloud.githubusercontent.com/assets/6026860/10660611/c321c052-78da-11e5-97e9-7d8d33dd70d3.png)

If better I can select the issue and press Delete to remove the issue from listing . 

Thanks

**Comment by dubeaud** [comment]
You have to click the issue title to go to the details screen and then delete the issue from there.
