### ISSUE TITLE
emails are not working in bugnet

### ISSUE THREAD

**Issue by sonikak** [dubeaud/bugnet#161]
Ho,

I have done all the smtp settings as well as tried with all ports 25,456,587 but emails are not working in bugnet.

Its showing
Failure sending mail.. Please see the error log for more details.

Please revert ASAP

**Comment by Petoj87** [comment]
What does the error log say?

**Comment by sonikak** [comment]
Hello,

 

I am not able to view Error log..As nothing is stored there.

 

Can you please let me know how to configure same

 

Regards,

Sandra

**Comment by sonikak** [comment]
Hello,



I am not able to view Error log..As nothing is stored there.



Can you please let me know how to configure same



Regards,

Sandra

**Comment by sonikak** [comment]
Its urgent

**Comment by dubeaud** [comment]
Can you tell us more about your configuration?
