### ISSUE TITLE
Reports of time logget by user

### ISSUE THREAD

**Issue by kaadner** [dubeaud/bugnet#163]
I've purchased a license for BugNet Pro, so I can show reports of time logged.

I can find a report, that shows the time logged for a specific project, but I also need to see a report for a specific user, during a given period of time (without having to run the report once for each project). Is that not possible? I can't seem to find a way to do that.

Best regards
Kristian

**Comment by dubeaud** [comment]
Hi,

The time logged by project is the only time tracking report right now and there is no way to narrow it down to a specific user. This would be a great addition though.

Regards.

**Comment by kaadner** [comment]
Thanks for the reply!
