### ISSUE TITLE
Creating a new user, no email received, can't reset passwords

### ISSUE THREAD

**Issue by dylanparry** [dubeaud/bugnet#168]
Hi,

I’m trying to create new user accounts. Creating the account is simple enough, and the new account is able to log in just fine. The problem I’m having is that I can’t seem to figure out how to get it to email the new user with their username and password, short of me emailing them manually.

If I click on the "random password" checkbox, then I obviously have no idea what that password is (and I don’t want to know either!) so I thought it’d email the new user details automatically. I thought maybe if I tried resetting the password then an email might get sent, but clicking on the "reset password" button gives me the following error:

"The password could not be changed, please verify that the password meets the password requirements."

I have set up the SMTP settings, and the test email goes through just fine. Am I missing another setting?

Thanks,

Dylan

**Comment by dubeaud** [comment]
Users can reset their password via the forgot password link. They are then
emailed a URL with a time limited reset token that they can enter a new
password.

We don't email user name and passwords for security reasons. The old
membership code did this but we have moved away from it.

**Comment by dylanparry** [comment]
Okay. So if I click on the "random password" button when creating a new user, how do they know I have created an account for them, and how do any of us know what the random password was? It doesn’t show it on the screen when creating the account, and doesn’t email it, so it seems there’s no way of finding out what it is.

**Comment by dubeaud** [comment]
If you uncheck random password you should be able to set the password.

**Comment by dylanparry** [comment]
When I check random password it grey the boxes out, and when I uncheck it they are still blank. Seems like it’s either not creating a random password at all, or just isn’t showing it to me. It’s not a massive issue—I’ll set my own temporary passwords and let users know to do a password reset before logging in.

**Comment by dubeaud** [comment]
The label should probably say random unknown password or display it to you
but it generates the password after you click the button to add the user so
it doesn't work the way you think it does.

**Comment by dylanparry** [comment]
Ah, I see. Thanks for clarifying that.

**Comment by dubeaud** [comment]
No problem. It's a little strange.
