### ISSUE TITLE
Clone project

### ISSUE THREAD

**Issue by dylanparry** [dubeaud/bugnet#171]
A couple of questions about the clone project feature.

I noticed that there was a commit 10 months ago which enabled cloning of the defaults for a project, as well as adding in the missing fields from milestones. This doesn't appear to be in the latest version though, and I’ve had to edit the stored procedure manually. Will this be included in the next release whenever that might be?

Secondly, when cloning a project the select menu to choose the project to clone appears to be ordered by project ID. Could this be changed to alphabetical order? I imagine that once I’ve got lots of projects it’ll become very awkward to find the correct one to clone if they’re in any other order than alphabetical.

**Comment by dubeaud** [comment]
That shouldn't be hard to do. A new release is long overdue with those bug fixes.

**Comment by dylanparry** [comment]
Thanks. I think there should also be the option to show inactive projects in the select menu. I’ve set up a template project that has everything set exactly as I want new projects to appear, but I’ve disabled it so it doesn’t appear in the projects list on the home page. That means it doesn’t show in the select menu for cloning projects, so I have to clone it from the edit page instead—not a big deal, but would be nice :)

**Comment by jmadkins** [comment]
Does this enhancement still need tackled?

**Comment by dubeaud** [comment]
No its done now, it should have been closed. Thanks though.
