### ISSUE TITLE
New install GUI / permision problem

### ISSUE THREAD

**Issue by dolenec** [dubeaud/bugnet#177]
Installation was OK.
I also set permission on folder on which all files are to IUSR (all persmision). Also I checked that folder is not read only... Also database is set correctly...
After install I have strange GUI - missing design. Also when I click to "Project" or other link inside page I get 404 error.

Can anybody tell me what to do? On IIS (7.5) I have Application Pool configured for .net 4, also this page works as Virtual page, so that domain is : www.domain.com/THISPAGE/

Don't know what to do, but I tried everything and now I'm out of ideas.

![1](https://cloud.githubusercontent.com/assets/16633222/12221389/93431900-b799-11e5-906f-29e76652fac1.png)
![2](https://cloud.githubusercontent.com/assets/16633222/12221390/93451cf0-b799-11e5-8ea5-66425df2380e.png)
![3](https://cloud.githubusercontent.com/assets/16633222/12221391/9345e4dc-b799-11e5-9540-cb6a8eb6ac8c.png)

**Comment by dolenec** [comment]
I also tried:
@@ -99,7 +99,7 @@
   </system.net>
   <system.webServer>
     <validation validateIntegratedModeConfiguration="false" />
-    <modules>
+    <modules runAllManagedModulesForAllRequests="true">
       
       

Error: 31 - but it stayes the same...

**Comment by dolenec** [comment]
If we will solve this quickly we will buy Pro version..

**Comment by dubeaud** [comment]
I am not sure what the issue is, usually the web.config change solves that issue for those experiencing it.

**Comment by dolenec** [comment]
So what now... Can I publish complete web.config that we try to fix problem?
I run this on Windows 2012 R2, SQL Express 2008 R2 SP3 and IIS 7.5

**Comment by dubeaud** [comment]
Are you running under the default wwwroot directory?

**Comment by dolenec** [comment]
no..
directory is:
D:/SShopBT/ ...

**Comment by dubeaud** [comment]
Have you tried wwwroot. I have run into problems with permissions switching the default IIS directory before unless your machine has already been setup and has other working applications on it.

**Comment by dolenec** [comment]
I have 36 different web pages, every in own folder.. some PHP (Joomla, Wordpress), some basic HTML and some ASP.NET, but this is the only one with problem...

**Comment by dubeaud** [comment]
Ok, looks like this could happen if the virtual paths conflict with the bundle names.  Here is one reference, http://thebeardeveloper.blogspot.ca/2013/02/403-forbidden-for-css-bundles-in-asp.html

You can try updating the bundle name in the bundle.config and then updating the Site.Master file and use something like styles\css for the bundle name.

**Comment by dolenec** [comment]
I will try that and I will report if this will fix the problems...

**Comment by dolenec** [comment]
Intresting... As new webpage, so that it is not virtual directory all is working fine...
