### ISSUE TITLE
how to upgrade from 1.5.265 to 1.6.339.0 

### ISSUE THREAD

**Issue by MCHALJJ** [dubeaud/bugnet#203]
are there instruction for upgrading from 1.5.265 to 1.6.339

**Comment by Novadys-IT** [comment]
It's pretty simple:

[https://github.com/dubeaud/bugnet/wiki/installing-bugnet#upgrading](url)

**Comment by MCHALJJ** [comment]
that didn't work for me, and I have tried to figure out why and I think I am just going to install BugNetPro but now a link under Alternate Installation Tutorial is not working."http://www.dotnetcamp.com/post/2012/10/20/How-to-install-BugNet.aspx" I am trying to install using the zip file. do you have another link to that ?

**Comment by MCHALJJ** [comment]
no help was given except by Novadys-IT, for non programers what is simple for them is not for non programmers.
