### ISSUE TITLE
Wrong Link To Issue On Calendar

### ISSUE THREAD

**Issue by dubeaud** [dubeaud/bugnet#42]
**This issue was imported from [CodePlex](http://bugnet.codeplex.com/workitem/287)**

**[nisav](http://www.codeplex.com/site/users/view/nisav)** wrote 2014-10-24 at 15:34
if you go to the Calendar page for any project and click on any Issue that's displayed, you will get an error "Application Error - /BugNET/Projects/Issues/IssueDetail.aspx".

the path to the page looks wrong 

looks like the fix is just to update the link to 

/BugNET/Issues/IssueDetail.aspx 

instead of 

/BugNET/Projects/Issues/IssueDetail.aspx

**[dubeaud](http://www.codeplex.com/site/users/view/dubeaud)** wrote 2014-10-27 at 10:34
What version are you running because I believe this was fixed in the latest version. You can see the support.bugnetproject.com calendar in September for an example
<a href="http://support.bugnetproject.com/Projects/ProjectCalendar.aspx?pid=1" rel="nofollow">
http://support.bugnetproject.com/Projects/ProjectCalendar.aspx?pid=1</a>

**[nisav](http://www.codeplex.com/site/users/view/nisav)** wrote 2014-10-27 at 10:49
bottom of page reads "Powered by BugNET 1.6.329.0"

**[nisav](http://www.codeplex.com/site/users/view/nisav)** wrote 2014-10-27 at 11:01
played around with it some more, it looks like it depends how you enter the calendar page.

i tried 2 ways

First i entered using the dropdown next to the project name on the homepage which took me to

BugNET/Projects/ProjectCalendar/9

i clicked on the issue in the calendar and received the error i posted about

In another tab i opened Project Summary page and then clicked Project -> Calendar which took me to

BugNET/Projects/ProjectCalendar.aspx?pid=9

i clicked on the issue in the calendar and was taken to the Issue Detail page (no errors)

it seems that it depends whch url format is used to load the calendar that cuases the issue.

ProjectCalendar/9 <- causes issue

ProjectCalendar.aspx?pid=9 <- works fine

**[dubeaud](http://www.codeplex.com/site/users/view/dubeaud)** wrote 2014-10-27 at 12:00
ok i get the same error now. Thanks. I will look into it.

**Comment by amolbmadake** [comment]
i have click bug list issue occurs-Application Error - /Issues/IssueDetail.aspx
please any one help me.
