### ISSUE TITLE
Bug: UserManager.HasPermission does not use passed in username in IsSuperUser()

### ISSUE THREAD

**Issue by aliciam** [dubeaud/bugnet#51]
IsSuperUser() gets the userName from HttpContext.Current.User.Identity.Name, essentially overriding the expected behaviour of the HasPermission(userName, projectId, permissionKey) method. Possibly not used elsewhere but incorrect behaviour nonetheless:

        public static bool HasPermission(string userName, int projectId, string permissionKey)  {
            ...
            if (IsSuperUser()) return true;

So just changed that line to ` if (IsSuperUser(userName)) return true;` added a new method, and changed the old one:

        /// <summary>
        /// Determines if the logged-in user is in the super user role
        /// </summary>
        /// <returns>
        /// <c>true</c> if is in role otherwise, <c>false</c>.
        /// </returns>
        public static bool IsSuperUser()
        {
            return IsSuperUser(HttpContext.Current.User.Identity.Name);
        }

        /// <summary>
        /// Determines if the supplied user is in the super user role
        /// </summary>
        /// <returns>
        /// <c>true</c> if is in role otherwise, <c>false</c>.
        /// </returns>
        public static bool IsSuperUser(string username)
        {
            if (string.IsNullOrEmpty(username))
            {
                return false;
            }

            var roles = RoleManager.GetForUser(username);
            return roles.Exists(r => r.Name == Globals.SUPER_USER_ROLE);
        }

**Comment by dubeaud** [comment]
Thanks for the pull request, this has been merged now.
