### ISSUE TITLE
IssueHistory change generated when saving empty "Assigned To" and "Owner"

### ISSUE THREAD

**Issue by aliciam** [dubeaud/bugnet#60]
When saving an existing issue, if the "Assigned to" (or "Owner") field is empty (both before and after a save) an IssueHistory is erroneously generated. 

This seems to be due to generating the history by comparing the username strings which are "none" (from Global.UNASSIGNED_DISPLAY_TEXT) in the new value and the localised string "Unassigned" in the old value.

**Comment by aliciam** [comment]
Change Global.UNASSIGNED_DISPLAY_TEXT to unassignedLiteral as defined below in the GetIssueChanges method solves the problem.

    var newAssignedUserName = String.IsNullOrEmpty(issueToCompare.AssignedUserName) ? unassignedLiteral : issueToCompare.AssignedUserName;

**Comment by aliciam** [comment]
Made a pull request for this: https://github.com/dubeaud/bugnet/pull/61

(sorry, new to Git so a few teething problems. Had? to go back to my master and make the changes there... couldn't just do pull request for changes in last commit as I'd hoped)

**Comment by dubeaud** [comment]
Thanks! all merged.
