### ISSUE TITLE
Custom fields for users

### ISSUE THREAD

**Issue by Petoj87** [dubeaud/bugnet#62]
Is there any chance you could add custom fields for users, and also if not possible allow to write something like [Firstname] [Lastname] [CustomField1] in Display Name and that the application then would replace the [] values with the values on the user? (this way you could actually make Display name global instead of per user.)

**Comment by Petoj87** [comment]
Also it would be nice if all information about a user would be shown when you put your mouse over their name while viewing a issue.

**Comment by dubeaud** [comment]
I have created a new issue for your second comment here https://github.com/dubeaud/bugnet/issues/64

**Comment by PeterDefendo** [comment]
I tried to implement this in the following fork -> https://github.com/PeterDefendo/bugnet but got stuck at the UserManager as it does not follow the same pattern that the IssueManager does, i guess the reason for this is that users are stored using the Membership provider and not your own DAL..
