### ISSUE TITLE
Changing date time format in web.config has no effect?

### ISSUE THREAD

**Issue by Petoj87** [dubeaud/bugnet#63]
Changing globalization in web.config has no effect?
i replaced en-US and en with sv-SE and sv
```<globalization culture="sv-SE" uiCulture="sv" requestEncoding="UTF-8" responseEncoding="UTF-8" fileEncoding="UTF-8" />```

But dates still show up in 1/7/2015 format instead of yyyy-MM-dd.

**Comment by dubeaud** [comment]
You will need to comment out the localization http module in the web.config, or add sv-SE to the list of supported translations in the database and update your profile to reflect that.

**Comment by Petoj87** [comment]
I changed ```<add name="LocalizationModule" type="BugNET.HttpModules.LocalizationModule, BugNET.HttpModules.Localization" />``` to ```<!--<add name="LocalizationModule" type="BugNET.HttpModules.LocalizationModule, BugNET.HttpModules.Localization" />-->``` but the date format is still incorrect.

**Comment by Petoj87** [comment]
Thanks by LocalizationModule in both system.webServer\modules and httpModules it worked!

**Comment by dubeaud** [comment]
Great!
