### ISSUE TITLE
Moved Database and I now get a 401.2 Access is denied

### ISSUE THREAD

**Issue by rhessinger** [dubeaud/bugnet#69]
I moved my database and bugnet files to a different machine and now i get a 401.2 access is denied error anytime i try and connect to it.  I am using AD auth.  I generated a machine key on the old computer and copied it out to the server and still no luck.  Any ideas?

**Comment by rhessinger** [comment]
I should also add that i could not restore my backup, so i ran a new installation to create the database structure and then synchronized the table data over.  Then i copied all the original bugnet files to teh new server.

**Comment by dubeaud** [comment]
This is usually caused by IIS and its authentication settings on the website,  make sure anonymous access is off, windows auth is checked in IIS.  If you are using a folder outside of the wwwroot, make sure your folder has all the proper permissions (compare with wwwroot folder).

**Comment by rhessinger** [comment]
Thanks.  I did miss that step so i corrected that.  But now I'm getting another error.

Server Error in '/BugNET' Application.

Invalid object name 'BugNet_P1_CFV'.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Data.SqlClient.SqlException: Invalid object name 'BugNet_P1_CFV'.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 


[SqlException (0x80131904): Invalid object name 'BugNet_P1_CFV'.]
   System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) +388
   System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) +815
   System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) +4515
   System.Data.SqlClient.SqlDataReader.TryConsumeMetaData() +69
   System.Data.SqlClient.SqlDataReader.get_MetaData() +134
   System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString) +6553981
   System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds) +6556619
   System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite) +586
   System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method) +104
   System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method) +288
   System.Data.SqlClient.SqlCommand.ExecuteReader() +302
   BugNET.Providers.DataProviders.SqlDataProvider.ExecuteReaderCmd(SqlCommand sqlCmd, GenerateListFromReader`1 gcfr, List`1& list) +158
   BugNET.Providers.DataProviders.SqlDataProvider.PerformQuery(List`1 queryClauses, ICollection`1 sortFields, Int32 projectId) +3081

[DataAccessException: Database Error]
   BugNET.Providers.DataProviders.SqlDataProvider.PerformQuery(List`1 queryClauses, ICollection`1 sortFields, Int32 projectId) +3523
   BugNET.BLL.IssueManager.PerformQuery(List`1 queryClauses, ICollection`1 sortColumns, Int32 projectId) +41
   BugNET._Default.rptProject_ItemDataBound(Object sender, RepeaterItemEventArgs e) +2011
   System.Web.UI.WebControls.Repeater.CreateItem(Int32 itemIndex, ListItemType itemType, Boolean dataBind, Object dataItem) +199
   System.Web.UI.WebControls.Repeater.CreateControlHierarchy(Boolean useDataSource) +659
   System.Web.UI.WebControls.Repeater.OnDataBinding(EventArgs e) +164
   BugNET._Default.Page_Load(Object sender, EventArgs e) +930
   System.Web.UI.Control.LoadRecursive() +71
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +3178

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.34212

**Comment by rhessinger** [comment]
Please ignore my last comment.  I followed the instructions in the discussion: http://bugnet.codeplex.com/discussions/392922 and that fixed my issue.
