### ISSUE TITLE
Huge defect numbers?

### ISSUE THREAD

**Issue by philwig** [dubeaud/bugnet#70]
I'm now on 1.6.339.0 (although see upgrade issues for that on the codeplex site).

I have noticed that i'm getting huge defect numbers when creating issues. So now, when I should be at about defect 2501 or so, I'm getting 32567 or something for the next defect number. I worry this is a sign that the sky is about to fall. Any thoughts, anyone?

--
Perhaps the link to the "support forum" from the BugNet site should point here not to Codeplex now?

**Comment by dubeaud** [comment]
I am not sure if it is related to this discussion at all https://bugnet.codeplex.com/discussions/450242

**Comment by philwig** [comment]
I would say that that is precisely the issue. So every time I upgrade the system, I'm going to get a 1,000 added to the next defect number. As I know know what the problem is, and that it's benign, I don't need to worry about it.

Naturally we're not using the numbers for any specific purpose - they are just "handles" on the tickets, so it does not matter to us.
