### ISSUE TITLE
Why is the latest GitHub release 1.6.327 instead of 1.6.339

### ISSUE THREAD

**Issue by efficiondave** [dubeaud/bugnet#71]
In CodePlex and on the BugNetProject site the latest release is 1.6.339 but on GitHub it's 1.6.327. GitHub should have the latest...

**Comment by dubeaud** [comment]
During the migration, the tool created those releases based on previous tags in Mercurial.  I will look into GitHub releases and moving the latest release over.

**Comment by dubeaud** [comment]
I have updated the releases section with the latest release, and will update the website and blog links.
