### ISSUE TITLE
Setup public continuous build 

### ISSUE THREAD

**Issue by dubeaud** [dubeaud/bugnet#72]
* Consider using appveyor to create a public CI build 
* Rewrite current nant build script in msbuild to create deployment artifacts

**Comment by dubeaud** [comment]
This is the current nant build script that can be converted to msbuild (trimmed down) and used on appveyor https://github.com/dubeaud/bugnet/blob/master/src/BugNET.build

**Comment by rms81** [comment]
I will try to help on this one.

**Comment by dubeaud** [comment]
Great!

**Comment by rms81** [comment]
@dubeaud, I´m not familiar with SQL Server Data Tools but it seems to me that makes sense to remove the BugNet.Database from the CI Build. What do you think?

**Comment by dubeaud** [comment]
@rms81 although I believe its supported in appveyor we don't use it for deployment so it would keep the build a bit faster if you left it out.

**Comment by dubeaud** [comment]
I modified this slightly after reviewing the appveyor docs.  I have moved the versioning to appveyor and the web deployment package gets created automatically.  I also moved the renaming of the latest data script to the project file beforebuild task.
