### ISSUE TITLE
Upgrade error after install - Procedure BugNet_Project_GetAllProjects has no parameters and arguments were supplied.

### ISSUE THREAD

**Issue by gilmaxter** [dubeaud/bugnet#77]
Hello upgraded my bugnet from version 1.4.256.0  to the latest one. and I seem to be getting a database error I cannot seem to resolve. 

Here is the error I am getting any advice on solving this would be appreciated and welcomed.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[SqlException (0x80131904): Procedure BugNet_Project_GetAllProjects has no parameters and arguments were supplied.]
   System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) +388
   System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) +810
   System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) +4403
   System.Data.SqlClient.SqlDataReader.TryConsumeMetaData() +82
   System.Data.SqlClient.SqlDataReader.get_MetaData() +135
   System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString) +6666037
   System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite) +6667856
   System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite) +577
   System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method) +107
   System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method) +288
   System.Data.SqlClient.SqlCommand.ExecuteReader() +302
   BugNET.Providers.DataProviders.SqlDataProvider.ExecuteReaderCmd(SqlCommand sqlCmd, GenerateListFromReader`1 gcfr, List`1& list) +162
   BugNET.Providers.DataProviders.SqlDataProvider.GetAllProjects(Nullable`1 activeOnly) +325
   BugNET._Default.Page_Load(Object sender, EventArgs e) +471
   System.Web.UI.Control.LoadRecursive() +71
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +3178

**Comment by dubeaud** [comment]
Did the upgrade complete successfully or were their errors?

**Comment by gilmaxter** [comment]
according to the install.aspx it was successful. Is there a install log I can refer to , for checking ?

**Comment by dubeaud** [comment]
I first try recycling the app / database if you haven't already. Here is the stored proc if you want to run it against your database again to update it.
''''sql
/****** Object:  StoredProcedure [dbo].[BugNet_Project_GetAllProjects]    Script Date: 11/2/2014 3:54:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[BugNet_Project_GetAllProjects]
	@ActiveOnly BIT = NULL
AS
SELECT 
	ProjectId,
	ProjectName,
	ProjectCode,
	ProjectDescription,
	AttachmentUploadPath,
	ProjectManagerUserId,
	ProjectCreatorUserId,
	DateCreated,
	ProjectDisabled,
	ProjectAccessType,
	ManagerUserName,
	ManagerDisplayName,
	CreatorUserName,
	CreatorDisplayName,
	AllowAttachments,
	AllowAttachments,
	AttachmentStorageType,
	SvnRepositoryUrl,
	AllowIssueVoting
FROM 
	BugNet_ProjectsView 
WHERE (@ActiveOnly IS NULL OR (ProjectDisabled = ~@ActiveOnly))
GO
''''

**Comment by gilmaxter** [comment]
I will certainly try it I will post results :)

**Comment by gilmaxter** [comment]
well I don't get the error anymore, but for some odd reason my Admin account wont accept my password.

**Comment by dubeaud** [comment]
Passwords were changed from encrypted to hashed passwords, you can either recovery your password through the forgot password function, or copy the machine key from your old web.config to the new one to keep the current keys which I believe should work.

**Comment by gilmaxter** [comment]
which old web.config file should I copy over I know theres a lot of those config files.

**Comment by dubeaud** [comment]
It would be the one in the root directly

**Comment by gilmaxter** [comment]
Are all the machine keys the same ? I can't seem to find the web.config file containing it. Would one from a fresh version 1.4.256.0 be the same ?

**Comment by dubeaud** [comment]
It should be in your existing web.config from before the upgrade.  You can't get it from the fresh install because it changed after you install.

**Comment by gilmaxter** [comment]
oh , I was able to find the older web.config file but having it overwrite the newer web.config file cause the default page to not function. is there a step I am suppose to if I just over-write the file ?

**Comment by dubeaud** [comment]
No , you only need to copy the machineKey,  the web.config has changed over the versions so thats all you need to copy across. This is just so you and your users do not have to reset passwords.

**Comment by gilmaxter** [comment]
I ended up just doing a password recovery, that solved the issue, and thank you for the stored proc.
