### ISSUE TITLE
Pulling total time from a project

### ISSUE THREAD

**Issue by gilmaxter** [dubeaud/bugnet#78]
I would have projects with various issues and I can see the total time it takes in the issue, but what if I want to total all the time from the issues assigned to the project ? How would I do that ? How is the sql server handling the times logged and how its connected to the issues. I am checking the server and all i can find is the Issue History table.

**Comment by dubeaud** [comment]
All the time tracking records reported against an issue are found in the IssueWorkReports table https://github.com/dubeaud/bugnet/blob/master/src/BugNET.Database/Tables/BugNet_IssueWorkReports.sql

**Comment by gilmaxter** [comment]
ty for the information :)
