### ISSUE TITLE
Feature request: Private Comments

### ISSUE THREAD

**Issue by robsiera** [dubeaud/bugnet#86]
My top feature request: "Private comments"

Basic implemenation as I see it:

    PrivateComments would become a RolePermission
    Roles with that permission
        will see a checkbox next to each comment and will be able to edit that checkbox
        will see the comments that are marked private

**Comment by aliciam** [comment]
There's an issue for that (previously suggested as "technical comments" but changed to "private comments" here: https://github.com/dubeaud/bugnet/issues/45

I've implemented them exactly as you suggested.

**Comment by dubeaud** [comment]
I will close this as a duplicate then.
