### ISSUE TITLE
Demo Admin Password

### ISSUE THREAD

**Issue by gilmaxter** [dubeaud/bugnet#93]
Hello I am trying to get into the Live demo , but it is not accepting the admin password stated on the website.
Username: admin
Password: password

Was the password changed or something or is the demo not accessible at this time ?

**Comment by dubeaud** [comment]
I have fixed it and you can log in now. Sometimes people change the password, and I don't have any sort of auto reset job setup.

**Comment by gilmaxter** [comment]
oh thank you for that :) do not know why someone would do that.

**Comment by sathishinwebz** [comment]
Hello I am trying to get into the Live demo , but it is not accepting the admin password stated on the website.
Username: admin
Password: password

Was the password changed or something or is the demo not accessible at this time ?

**Comment by sathishinwebz** [comment]
http://demo.bugnetproject.com/Account/Login
