### ISSUE TITLE
Password problems after upgrading from 1.1

### ISSUE THREAD

**Issue by argenacho** [dubeaud/bugnet#94]
After upgrading (with no error messages, on the same server) I couldn´t login with any account. I had to manually reset the admin password as mentioned here: http://brutaldev.com/post/reset-bugnet-admin-password , and after that I went and try to change other user´s password from the admin GUI but got the following message:

 The password could not be changed, please verify that the password meets the password requirements

I tried very complex passwords and still kept getting the same message. All in all, my bugnet install is not accesible after upgrading.

**Comment by dubeaud** [comment]
You can find the password requirements in the web.config 
The default is a length of 7 characters.

```xml
<add name="ExtendedSqlMembershipProvider" type="BugNET.Providers.MembershipProviders.ExtendedSqlMembershipProvider, BugNET.Providers.MembershipProviders.ExtendedSqlMembershipProvider" connectionStringName="BugNET" description="Extended Membership API" enablePasswordRetrieval="false" enablePasswordReset="true" requiresQuestionAndAnswer="false" requiresUniqueEmail="false" applicationName="BugNET" maxInvalidPasswordAttempts="5" minRequiredPasswordLength="7" minRequiredNonalphanumericCharacters="0" passwordAttemptWindow="10"/>
```

**Comment by argenacho** [comment]
Is not that, trust me. I tried with the most complex passwords possible, that were way above the minimum requirements, and the only way we were able to change the pwd after the upgrade was by using code. Once we did that, the pwd change from the UI worked as expected, but I still think there's a problem with the version upgrade.

**Comment by dubeaud** [comment]
The password reset in the admin section works slightly differently, the best way of course is to use the forgot password function.  The admin UI is really left over from when passwords were encrypted.

**Comment by dubeaud** [comment]
Did you resolve this?

**Comment by argenacho** [comment]
I solved it by using Forms Authentication code to reset the admin pwd, and then used the admin GUI to reset every other user pass. None of the passwords were working after doing a regular update with no errors.

**Comment by dubeaud** [comment]
Still strange but glad you got it working.

**Comment by kiddailey** [comment]
This should not be closed.  I've been trying for a while now to upgrade from 1.1.213 without success due to SQL upgrade errors and after figuring out how to get the upgrade scripts to work (1.6.339 script fails multiple times due to missing stored procedures) I've now run into this issue of not being able to log in.

@argenacho - Can you detail the steps that you're referring to with "by using Forms Authentication code to reset the admin pwd"?
