### ISSUE TITLE
Expanding Project Summary

### ISSUE THREAD

**Issue by gilmaxter** [dubeaud/bugnet#99]
Hello,

I plan on adding a new section to project summary called "phases (open issues)". There is a new table i made called project phases and a column has been added to issues and projects.

When a phase is set to a project the project phase will be recorded on the issue as the time it was set to that when when the project phase changes the issue will have that project phase saved still on the issue. Now the last thing i am working on to this enchancement is i am trying to figure out how to add the section into project summary and on the issue list. But for now its on the project summary. Any advise on how to start this and where to go would be appreciated alot :)  

Thank you

**Comment by gilmaxter** [comment]
Ended up doing this on a seperate page and just sql it to show the results. Not to bad. thank you.

**Comment by dubeaud** [comment]
That would work.   Adding it in the context of the current application would require
1. new stored proc
2. modify data access layer to add new method to call the new stored proc
3. adding business manager method and entity
4. Update UI to call the business manager and get data.

This is just FYI , so whatever works best for you.
